import type { MenuCategory } from "@/types";

export const menuCategories: MenuCategory[] = [
  {
    id: "weekend-deals",
    label: "🔥 Weekend Deals",
    note: "Available Sat–Sun only",
    items: [
      {
        name: "Halwa Poori Combo",
        desc: "Semolina halwa + crispy poori + 3 choly (chickpea curry). Weekend breakfast staple.",
        price: 12.99,
        badge: "Weekend Only",
        image: "halwa-puri",
      },
      {
        name: "Halwa Poori + Qeema",
        desc: "Classic halwa poori with spiced ground beef qeema.",
        price: 14.99,
        badge: "Weekend Only",
        image: "halwa-puri-keema",
      },
      {
        name: "Special Weekend Biryani Tray",
        desc: "Family-style biryani tray — chicken or beef, serves 3–4.",
        price: 34.99,
        badge: "Weekend Deal",
        image: "biryani-tray",
      },
    ],
  },
  {
    id: "biryani",
    label: "🍛 Biryani",
    note: "Our most famous dishes — recipes from Karachi",
    items: [
      {
        name: "Chicken Biryani",
        desc: "Fragrant basmati rice layered with tender halal chicken, whole spices, caramelized onions & raita.",
        price: 13.99,
        badge: "Best Seller",
        image: "chicken-biryani",
      },
      {
        name: "Beef Biryani",
        desc: "Slow-cooked beef with aged basmati, fried onions, and a blend of whole Karachi spices.",
        price: 14.99,
        badge: "Fan Favorite",
        image: "beef-biryani",
      },
      {
        name: "Nalli Beef Biryani",
        desc: "Bone-in beef nalli (shank) biryani — rich marrow flavor, slow cooked for hours.",
        price: 16.99,
        badge: "Chef's Special",
        image: "nalli-biryani",
      },
      {
        name: "Lamb Shank Biryani",
        desc: "Tender lamb shank on a bed of aromatic long-grain basmati with saffron notes.",
        price: 17.99,
        badge: "Premium",
        image: "lamb-biryani",
      },
      {
        name: "Mutton Yakni Pulao",
        desc: "Delicately spiced mutton pulao cooked in rich bone broth. Lighter than biryani, equally satisfying.",
        price: 15.99,
        badge: "",
        image: "mutton-pulao",
      },
      {
        name: "Vegetable Biryani",
        desc: "Seasonal vegetables in fragrant basmati, cooked in dum style.",
        price: 10.99,
        badge: "",
        image: "veg-biryani",
      },
    ],
  },
  {
    id: "kabab-rolls",
    label: "🌯 Kabab Rolls",
    note: "Silver Spoon style — Karachi's street rolls",
    items: [
      {
        name: "Bihari Kabab Roll",
        desc: "Juicy, smoky Bihari kababs in soft flaky paratha with chutney, onions & peppers. Comes with a free soda.",
        price: 10.99,
        badge: "Signature",
        image: "bihari-kabab-roll",
      },
      {
        name: "Chicken Tikka Roll",
        desc: "Marinated chicken tikka, chargrilled, wrapped in fresh paratha with mint chutney.",
        price: 9.99,
        badge: "",
        image: "chicken-tikka-roll",
      },
      {
        name: "Seekh Kabab Roll",
        desc: "Hand-minced beef seekh kabab, flame-grilled, served in paratha with raita.",
        price: 10.99,
        badge: "",
        image: "seekh-kabab-roll",
      },
      {
        name: "Chapli Kabab Roll",
        desc: "Peshawar-style chapli kabab with tomato, coriander in grilled paratha.",
        price: 10.99,
        badge: "",
        image: "chapli-kabab",
      },
      {
        name: "Chicken Roll",
        desc: "Crispy fried or grilled chicken strips in a soft paratha wrap with house sauce.",
        price: 8.99,
        badge: "",
        image: "chicken-roll",
      },
    ],
  },
  {
    id: "fried-chicken-fish",
    label: "🍗 Fried Chicken & Fish",
    note: "Crispy, spiced, always fresh — never frozen",
    items: [
      {
        name: "Halal Fried Chicken (2pc)",
        desc: "Bone-in halal fried chicken — crispy spiced crust, juicy inside. Served with dipping sauce.",
        price: 8.99,
        badge: "",
        image: "fried-chicken",
      },
      {
        name: "Halal Fried Chicken (4pc)",
        desc: "Four pieces of our signature crispy halal fried chicken.",
        price: 14.99,
        badge: "Popular",
        image: "fried-chicken-4pc",
      },
      {
        name: "Chicken Leg Piece",
        desc: "Marinated whole chicken leg, fried to golden perfection.",
        price: 5.99,
        badge: "",
        image: "chicken-leg",
      },
      {
        name: "Paplet Fish (Pomfret)",
        desc: "Whole pomfret fish — marinated in Pakistani spices, fried crisp. A true Karachi coastal classic.",
        price: 15.99,
        badge: "Karachi Classic",
        image: "paplet-fish",
      },
      {
        name: "Fish Fry",
        desc: "Fresh fish fillet fried in our spiced batter. Served with chutney and fries.",
        price: 13.99,
        badge: "",
        image: "fish-fry",
      },
      {
        name: "Masala Fries",
        desc: "Crispy fries tossed in our signature Pakistani masala spice blend. Addictive.",
        price: 6.99,
        badge: "Must Try",
        image: "masala-fries",
      },
    ],
  },
  {
    id: "hot-wings",
    label: "🔥 Hot Wing Specials",
    note: "Sauced, spiced & impossible to share",
    items: [
      {
        name: "6-Piece Wings",
        desc: "Six Zabiha halal chicken wings in your choice of sauce: Buffalo · Honey Gold · Desi Masala · BBQ.",
        price: 13.95,
        badge: "Best Value",
        image: "wings-6pc",
      },
      {
        name: "12-Piece Wings",
        desc: "A full dozen wings. Great for sharing — if you're feeling generous.",
        price: 24.95,
        badge: "",
        image: "wings-12pc",
      },
      {
        name: "Desi Masala Wings (6pc)",
        desc: "Our house Pakistani masala rub baked into the wings. No sauce needed.",
        price: 14.95,
        badge: "Signature",
        image: "desi-wings",
      },
    ],
  },
  {
    id: "burgers",
    label: "🍔 Burgers",
    note: "Zabiha halal beef & chicken patties, always fresh",
    items: [
      {
        name: "Chicken Zinger Burger",
        desc: "Crispy spiced chicken fillet, lettuce, tomato, house zinger sauce on a brioche bun.",
        price: 11.95,
        badge: "Fan Favorite",
        image: "zinger-burger",
      },
      {
        name: "Beef Burger",
        desc: "Juicy halal beef patty, cheddar, lettuce, tomato, pickles, special house sauce.",
        price: 11.95,
        badge: "",
        image: "beef-burger",
      },
      {
        name: "Philly Cheesesteak",
        desc: "Shaved halal beef, sautéed peppers, onions, melted cheese in a hoagie roll.",
        price: 11.95,
        badge: "",
        image: "philly-cheesesteak",
      },
      {
        name: "Double Beef Burger",
        desc: "Two halal beef patties, double cheese, caramelized onions, special sauce.",
        price: 14.95,
        badge: "",
        image: "double-burger",
      },
    ],
  },
  {
    id: "appetizers",
    label: "🥗 Appetizers",
    note: "Start your meal the right way",
    items: [
      {
        name: "Chicken Karhai",
        desc: "Bone-in chicken slow-cooked in a wok (karhai) with tomatoes, ginger, garlic & whole spices. Served with naan.",
        price: 15.99,
        badge: "Karachi Style",
        image: "chicken-karahi",
      },
      {
        name: "Beef Nihari",
        desc: "Slow-simmered beef shank in a rich spiced broth — the ultimate Karachi breakfast/dinner dish.",
        price: 15.99,
        badge: "Karachi Classic",
        image: "beef-nihari",
      },
      {
        name: "Chana Cholay",
        desc: "Spiced chickpeas cooked in a tangy tomato-onion base. Served with naan or paratha.",
        price: 8.99,
        badge: "",
        image: "chana-cholay",
      },
      {
        name: "Qeema (Ground Beef)",
        desc: "Spiced Pakistani-style ground beef. Great as a side or in a roll.",
        price: 9.99,
        badge: "",
        image: "keema",
      },
      {
        name: "Naan (Plain)",
        desc: "Fresh tandoor-baked naan.",
        price: 1.99,
        badge: "",
        image: "naan",
      },
      {
        name: "Naan (Butter/Garlic)",
        desc: "Warm naan brushed with butter and garlic.",
        price: 2.99,
        badge: "",
        image: "garlic-naan",
      },
      {
        name: "Paratha",
        desc: "Layered, flaky whole-wheat flatbread.",
        price: 2.99,
        badge: "",
        image: "paratha",
      },
    ],
  },
  {
    id: "kids-menu",
    label: "🧒 Kids Menu",
    note: "Smaller portions, same great flavors",
    items: [
      {
        name: "Kids Chicken Biryani",
        desc: "A half portion of our famous chicken biryani, mild spiced for younger palates.",
        price: 7.99,
        badge: "",
        image: "kids-biryani",
      },
      {
        name: "Kids Fried Chicken (1pc)",
        desc: "One piece of our crispy halal fried chicken with fries.",
        price: 5.99,
        badge: "",
        image: "kids-fried-chicken",
      },
      {
        name: "Kids Chicken Roll",
        desc: "Mini chicken roll — great for small hands.",
        price: 5.99,
        badge: "",
        image: "kids-chicken-roll",
      },
    ],
  },
  {
    id: "desserts-drinks",
    label: "🍮 Desserts & Drinks",
    note: "End on something sweet",
    items: [
      {
        name: "Halwa (Semolina Pudding)",
        desc: "Sweet, aromatic semolina halwa with cardamom, saffron and nuts. Also served in weekend Halwa Poori combo.",
        price: 4.99,
        badge: "Weekend Staple",
        image: "halwa",
      },
      {
        name: "Kheer (Rice Pudding)",
        desc: "Slow-cooked creamy rice pudding with cardamom and rose water.",
        price: 4.99,
        badge: "",
        image: "kheer",
      },
      {
        name: "Chai (Desi Tea)",
        desc: "Authentic Pakistani desi chai — milk tea with cardamom and ginger.",
        price: 2.99,
        badge: "Must Have",
        image: "desi-chai",
      },
      {
        name: "Lassi (Sweet)",
        desc: "Chilled blended yoghurt drink, lightly sweetened.",
        price: 3.99,
        badge: "",
        image: "lassi",
      },
      {
        name: "Soda",
        desc: "Pepsi · 7UP · Mountain Dew · Water",
        price: 1.99,
        badge: "",
        image: "soda",
      },
    ],
  },
  {
    id: "winter-specials",
    label: "❄️ Winter Specials",
    note: "Warming dishes for colder months",
    items: [
      {
        name: "Paye (Trotters Soup)",
        desc: "Slow-cooked bone broth soup with beef trotters — warming, collagen-rich, deeply spiced.",
        price: 14.99,
        badge: "Seasonal",
        image: "paye-soup",
      },
      {
        name: "Haleem",
        desc: "Slow-cooked wheat, lentils and beef slow-simmered for hours into a rich, thick stew.",
        price: 13.99,
        badge: "Seasonal",
        image: "haleem",
      },
      {
        name: "Aloo Gosht",
        desc: "Tender beef with potatoes in a slow-cooked spiced gravy. Comfort food at its finest.",
        price: 14.99,
        badge: "",
        image: "aloo-gosht",
      },
    ],
  },
];
